# fly.toml app configuration file generated for twitter-backend-7u7ygq on 2024-12-23T09:43:28Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'twitter-backend-7u7ygq'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
